name: "🐶🐰 Pet-a-Day"
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-avatar:
    runs-on: ubuntu-latest
    steps:
    - uses: darcyclarke/pet-a-day-action@v1.0.4
      with:
        email:  ${{ secrets.EMAIL }}
        password: ${{ secrets.PASSWORD }}
