name: "🐶 Pet-a-Day"
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-avatar:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/pet-a-day-action@v1.0
      with:
        email:  ${{ secrets.EMAIL }}
        password: ${{ secrets.PASSWORD }}
