name: "Create npm PR"
on:
  push:
    branches:
      - master
permissions: read-all|write-all
jobs:
  create-pr:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: gh repo clone npm/node
      