name: "Test GitHub CLI"
on:
  push:
    branches:
      - master
jobs:
  update-avatar:
    runs-on: ubuntu-latest
    steps:
      - name: clone npm's node
        run: |
          gh repo clone npm/node
